In [1]:
import numpy as np

In [2]:
np.__version__

'2.4.6'

## Create and Read

#### 1D Array

In [6]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [7]:
type(arr1)

numpy.ndarray

In [8]:
arr1.shape

(5,)

In [9]:
arr1.dtype

dtype('int64')

In [10]:
arr1.ndim

1

In [11]:
arr1.size

5

#### 2D Array

In [12]:
arr2 = np.array([[1,4,5], [6,7,4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [13]:
arr2.ndim

2

In [15]:
arr2.shape #(row, column)

(2, 3)

In [16]:
arr2.dtype

dtype('int64')

In [17]:
arr2.size

6

#### 3D Array

In [24]:
arr3 = np.array([[[1,4,5], [6,7,4]],[[3,4,5],[5,8,7]],[[1,4,5], [6,7,4]]])
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 4, 5],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [25]:
arr3.ndim

3

In [26]:
arr3.shape  #

(3, 2, 3)

In [27]:
arr3.size


18

### Create Random Array

In [29]:
randomArr = np.random.rand(3,2,3)
randomArr

array([[[0.84729045, 0.91606227, 0.90165089],
        [0.16431088, 0.52668835, 0.4032544 ]],

       [[0.65230441, 0.00575775, 0.83289782],
        [0.86273964, 0.45042709, 0.38758216]],

       [[0.33135822, 0.63873013, 0.60583905],
        [0.85343744, 0.33187962, 0.69410739]]])

In [30]:
randomArr.dtype

dtype('float64')

In [32]:
zeroes = np.zeros((3,2,3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [33]:
zeroes.ndim

3

In [34]:
full = np.full((3,2,3),9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [59]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 4, 5],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [78]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 4, 5],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [80]:
arr3[0,0,2] = 500
arr3

array([[[  1,   4, 500],
        [  6,   7,   4]],

       [[  3,   4,   5],
        [  5,   8,   7]],

       [[  1,   4,   5],
        [  6,   7,   4]]])

In [81]:
arr3.sort()
arr3

array([[[  1,   4, 500],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  5,   7,   8]],

       [[  1,   4,   5],
        [  4,   6,   7]]])

In [83]:
# Reshape
arr3.shape

(3, 2, 3)

In [87]:
arr3_reshape = arr3.reshape((2,3,-1))
arr3_reshape

array([[[  1,   4, 500],
        [  4,   6,   7],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  1,   4,   5],
        [  4,   6,   7]]])

In [86]:
arr3_reshape.shape

(2, 3, 3)

#### Appending & Inserting

In [88]:
new_array = np.ones((3,2,3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [90]:
appd = np.append(zeroes, new_array, axis=0) # axis 0 = row, axis 1 = column
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
# Insert

In [91]:
zeroes, new_array

(array([[[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]]]),
 array([[[1., 1., 1.],
         [1., 1., 1.]],
 
        [[1., 1., 1.],
         [1., 1., 1.]],
 
        [[1., 1., 1.],
         [1., 1., 1.]]]))

In [92]:
inserted_array = np.insert(zeroes, 1, new_array, axis = 0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

#### Delete

In [93]:
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.72721855, 0.6192146 , 0.00832163],
        [0.47591832, 0.84305855, 0.16638766]],

       [[0.90084097, 0.55896481, 0.12395763],
        [0.39649886, 0.20301618, 0.58368684]],

       [[0.14146381, 0.02919366, 0.90320149],
        [0.01712789, 0.52093085, 0.85197687]]])

In [96]:
# delete the array
arr5 = np.delete(arr4, 0, axis=1)
arr5

array([[[0.47591832, 0.84305855, 0.16638766]],

       [[0.39649886, 0.20301618, 0.58368684]],

       [[0.01712789, 0.52093085, 0.85197687]]])

In [ ]:
np.save

In [60]:
arr3[0]

array([[1, 4, 5],
       [6, 7, 4]])

In [61]:
arr3[0:2]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 4, 5],
        [5, 8, 7]]])

In [62]:
arr3[-1]

array([[1, 4, 5],
       [6, 7, 4]])

In [63]:
arr3[1,0,1]

np.int64(4)

#### Update & Delete

In [64]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)


In [65]:
a1

array([[[0.83461788, 0.47088669],
        [0.90149635, 0.23073012],
        [0.22714326, 0.25859174]],

       [[0.70377462, 0.29111556],
        [0.85737331, 0.09686695],
        [0.66580976, 0.35465027]]])

In [66]:
a2

array([[[0.54164686, 0.20569871],
        [0.17241889, 0.58474053],
        [0.1340015 , 0.45393371]],

       [[0.67319266, 0.06394408],
        [0.78445002, 0.72327114],
        [0.43822495, 0.00187276]]])

#### Basic Math Operations

In [67]:
np.add(a1, a2)

array([[[1.37626474, 0.6765854 ],
        [1.07391524, 0.81547065],
        [0.36114476, 0.71252545]],

       [[1.37696728, 0.35505963],
        [1.64182333, 0.82013809],
        [1.10403471, 0.35652303]]])

In [68]:
np.subtract(a1,a2)

array([[[ 0.29297103,  0.26518799],
        [ 0.72907746, -0.35401042],
        [ 0.09314176, -0.19534197]],

       [[ 0.03058197,  0.22717148],
        [ 0.07292329, -0.62640418],
        [ 0.22758481,  0.3527775 ]]])

In [69]:
np.divide(a1,a2)

array([[[1.54088937e+00, 2.28920590e+00],
        [5.22852429e+00, 3.94585470e-01],
        [1.69508002e+00, 5.69668502e-01]],

       [[1.04542825e+00, 4.55265879e+00],
        [1.09296104e+00, 1.33928960e-01],
        [1.51933331e+00, 1.89372694e+02]]])

In [70]:
np.multiply(a1,a2)

array([[[4.52068155e-01, 9.68607841e-02],
        [1.55434999e-01, 1.34917253e-01],
        [3.04375375e-02, 1.17383506e-01]],

       [[4.73775906e-01, 1.86151149e-02],
        [6.72566511e-01, 7.00610699e-02],
        [2.91774448e-01, 6.64176076e-04]]])

#### Satistical Operations

In [71]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [72]:
sqrt

np.float64(5.0)

In [73]:
abs

np.int64(2)

In [74]:
power

np.int64(256)

In [75]:
log

np.float64(3.2188758248682006)

In [76]:
mins

np.float64(0.09686695133348133)

In [77]:
maxs

np.float64(0.7844500199607376)

#### Update